import type { CampaignReport } from './archive';

const statuses = { 'screen-bracketed': 'Screen bracket observed', 'unbounded-above': 'Upper boundary unmeasured', 'unbounded-below': 'Lower boundary unmeasured', inconclusive: 'Inconclusive' };

export default function CampaignReports({ reports }: { reports: CampaignReport[] }) {
  if (!reports.length) return null;
  return <section className="archive-comparison" aria-labelledby="campaign-reports-title"><h2 id="campaign-reports-title">Saved campaign reports</h2><p className="figure-note">Reports below match the indexed request-file hashes and saved summaries. Repeated fixed-window screens do not establish sustainable capacity.</p>{reports.map((report) => <details className="archive-provenance" key={report.sha256}><summary>{report.campaignId} · {report.purpose === 'integration' ? 'Integration only' : report.purpose} · {report.runCount} runs</summary>
    {report.purpose === 'integration' && <p className="figure-note">Pipeline validation only. These measurements do not establish GPU/model performance.</p>}
    {report.runKind === 'isolated' ? <p className="figure-note">Isolated serial requests have no offered arrival rate. Open-loop capacity screens do not apply; the recorded rate setting is only a placeholder.</p> : report.runKind === null ? <p className="figure-note">Arrival mode is unavailable. No offered-load capacity screen is shown.</p> : report.capacityBrackets.length ? report.capacityBrackets.map((bracket) => <div key={bracket.variant}><h3>{bracket.variant}: {statuses[bracket.status]}</h3><p className="figure-note">Highest tested rate with all trials passing: {bracket.highestAllPassRate ?? 'unavailable'} requests/s. Lowest tested rate with all trials failing: {bracket.lowestAllFailRate ?? 'unavailable'} requests/s.</p><div className="table-scroll" tabIndex={0} role="region" aria-label={`${bracket.variant} repeated capacity screens`}><table><thead><tr><th scope="col">Offered / s</th><th scope="col">Trials / prescribed</th><th scope="col">Saved screen</th></tr></thead><tbody>{bracket.points.map((point) => <tr key={point.offeredRps}><th scope="row">{point.offeredRps}</th><td>{point.trialCount} / {point.expectedTrialCount ?? 'not specified'}</td><td>{point.classification}</td></tr>)}</tbody></table></div><ul className="evidence-notes">{bracket.reasons.map((reason) => <li key={reason}>{reason}</li>)}{bracket.points.flatMap((point) => point.reasons.map((reason) => <li key={`${point.offeredRps}:${reason}`}>{point.offeredRps} requests/s: {reason}</li>))}</ul></div>) : <p className="figure-note">This report does not include repeated capacity screens.</p>}
    <ul className="evidence-notes">{report.limitations.map((limitation) => <li key={limitation}>{limitation}</li>)}</ul>{report.downloadPath && <><p><a href={report.downloadPath} download>Download verified report JSON ↓</a></p><code className="workload-hash">SHA-256: {report.sha256}</code></>}
  </details>)}</section>;
}
